language: node_js

node_js:
  - "0.10"

dist: xenial
sudo: required
services:
  - xvfb

branches:
  only:
  - test_travisci 

addons:
  chrome: stable

stages:
  - run nightwatch tests

before_install:
  # fire up xvfb on port :99.0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - npm install -g nightwatch
  - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/bin
  - echo "chromedriver is here!"
  - which chromedriver


install:
  - echo "nothing to install"
  # install a sh on this vm which would connect to our indexer and install Q-Audit to run tests against this server???

jobs:
  include:
    - stage: run nightwatch tests
      name: Run nightwatch tests on Q-Audit
      script:
        #in the nightwatch config give the following flags for headless mode --headless --disable-gpu 
        - ./nightwatch tests/q_audit_tests.js

after_success:
  - echo "merging pull request of release candidate into master"
  - #merge the pull request of the release candidate into master

notifications:
  email:
    recipients:
      # the slack channel email
      - mfocella@qmulos.com
    on_success: always # default: change
    on_failure: always # default: always
