version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "Install dependancies for Tests and Deploy release candidate to SH"
      - echo `pwd`
      - echo `ls`
      - npm install -g nightwatch
      - npm install -g chromedriver
      # Run the Nightwatch deploy to SH and test it was successful script
      #-nightwatch deploys/q_compliance_deploy_n_test.js
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "Run FrontEnd Nightwatch tests"
      #- nightwatch tests/q_compliance_tests.js
  post_build:
    commands:
      - echo "post_build_step"
      #if front end tests pass then merge releasecandidate branch to master
