version: 2
jobs:
  build:
    branches:
        only:
          -test_circle_ci
    machine: true
    working_directory: /test_dir
    steps:
      # Docker is preinstalled, along with docker-compose
      - checkout

      # start proprietary DB using private Docker image
      - run: |
          docker login -u $q_USER -p $q_PASS
          docker run -d -p 8000:8000 -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=qmulosqmulos' mfocella/q_splunk_n_night:q_auditv3
      # Download and configure Qmulos apps
      - run: 
        name: "Download newest version of Qmulos apps and configure"
        command: "./configure_qaudit.sh"

      - run:
        name: "Run Nightwatch Front End tests"
        command: "nightwatch /home/splunk/nightwatch_q_app_frontend_testing/q_audit_tests.js"
